name: "SkyLite UX"
description: "Self-hosted family manager (Calendar, Todos, Shopping Lists)"
version: "0.0.5"
webui: "http://[HOST]:[PORT:3000]/"
slug: "skylite-ux"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: false
panel_icon: "mdi:calendar"
panel_title: "SkyLite UX"
map:
  - config:rw
options:
  database_url: "postgresql://user:password@HOSTNAME:5432/DATABASENAME"
schema:
  database_url: "str?"
ports:
  "3000/tcp": 3000
discovery:
  - postgresql
